name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --verbosity normal

    - name: SonarCloud Analysis
      if: ${{ github.event_name == 'push' }}  # Only run SonarCloud analysis on push events
      uses: sonarsource/sonarcloud-github-action@v1
      with:
        organization: 'teammatetinder'  # Your SonarCloud organization key
        token: ${{ secrets.SONAR_TOKEN }}
        projectKey: 'TeammateTinder_MatchService'  # Your SonarCloud project key
